version: '3.8'

services:
  workspace:
    build: .
    image: workspace-fastapi:latest
    command:  
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/test
    depends_on:
      - postgres
  

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
