"""Initial migration

Revision ID: aecbe4f18125
Revises: 734e293535c2
Create Date: 2024-05-03 21:39:18.463807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecbe4f18125'
down_revision: Union[str, None] = '734e293535c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('modifiedBy', sa.String(), nullable=True))
    op.alter_column('users', 'createdBy',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'createdBy',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('users', 'modifiedBy')
    op.drop_column('users', 'createdAt')
    # ### end Alembic commands ###
